version: '3.8'

services:
  agno-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: agno-app
    environment:
      DATABASE_URL: ${DATABASE_URL:-postgres://postgres:AkqT0Q5kVnCXyIgYPXc2SsTmljgI1DuOTpiXoS5tVAHjl1zKQFFEAYUvlT3pht5k@j8k08cosc8k0g0s0wcsocogo:5432/postgres}
      DB_URL: ${DATABASE_URL:-postgres://postgres:AkqT0Q5kVnCXyIgYPXc2SsTmljgI1DuOTpiXoS5tVAHjl1zKQFFEAYUvlT3pht5k@j8k08cosc8k0g0s0wcsocogo:5432/postgres}
      AGENTOS_DATABASE_URL: ${DATABASE_URL:-postgres://postgres:AkqT0Q5kVnCXyIgYPXc2SsTmljgI1DuOTpiXoS5tVAHjl1zKQFFEAYUvlT3pht5k@j8k08cosc8k0g0s0wcsocogo:5432/postgres}
      AGENTOS_VECTOR_DB_URL: ${DATABASE_URL:-postgres://postgres:AkqT0Q5kVnCXyIgYPXc2SsTmljgI1DuOTpiXoS5tVAHjl1zKQFFEAYUvlT3pht5k@j8k08cosc8k0g0s0wcsocogo:5432/postgres}
      PORT: 80
      HOST: 0.0.0.0
      RUNTIME_ENV: production
      PYTHONUNBUFFERED: 1
      PYTHONPATH: /app
      OPENAI_API_KEY: ${OPENAI_API_KEY:-}
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY:-}
      GOOGLE_API_KEY: ${GOOGLE_API_KEY:-}
      GROQ_API_KEY: ${GROQ_API_KEY:-}
      PERPLEXITY_API_KEY: ${PERPLEXITY_API_KEY:-}
      XAI_API_KEY: ${XAI_API_KEY:-}
      OPENROUTER_API_KEY: ${OPENROUTER_API_KEY:-}
    restart: unless-stopped
    volumes:
      - app_data:/app/data
      - app_storage:/app/storage
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 15s
      retries: 3
      start_period: 120s

volumes:
  app_data:
    driver: local
  app_storage:
    driver: local
