version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+psycopg://agno:agno@db:5432/agno
      - OPENAI_API_KEY=${OPENAI_API_KEY:?}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:?}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY:?}
      - GROQ_API_KEY=${GROQ_API_KEY:?}
      - PERPLEXITY_API_KEY=${PERPLEXITY_API_KEY:?}
      - XAI_API_KEY=${XAI_API_KEY:?}
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY:?}
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - app_storage:/app/storage

  db:
    image: pgvector/pgvector:pg16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=agno
      - POSTGRES_USER=agno
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-agno}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U agno -d agno"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data:
  app_storage:
